[workspace]
authors = ["chuan.peng <erichuanp@gmail.com>"]
channels = ["conda-forge"]
name = "AddToView"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
opencv = ">=4.12.0,<5"
pip = ">=25.2,<26"
requests = ">=2.32.5,<3"
